export const WALLET_CREATE_REQUEST = "WALLET_CREATE_REQUEST";
export const WALLET_CREATE_SUCCESS = "WALLET_CREATE_SUCCESS";
export const WALLET_CREATE_FAIL = "WALLET_CREATE_FAIL";

export const WALLET_CREATE_RESET = "WALLET_CREATE_RESET";

export const WALLET_EDIT_REQUEST = "WALLET_EDIT_REQUEST";
export const WALLET_EDIT_SUCCESS = "WALLET_EDIT_SUCCESS";
export const WALLET_EDIT_FAIL = "WALLET_EDIT_FAIL";

export const WALLET_EDIT_RESET = "WALLET_EDIT_RESET";
